name: traffic
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda
  - pip
  - torchaudio
  - torchvision
  - matplotlib
  - pip:
      - ultralytics
      - gdown
      - transformers
      - datasets
      - peft
      - accelerate
      - bitsandbytes